
################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libwasmtime,$(CONFIG_LIBWASMTIME)))

################################################################################
# Per-library cargo flags: force the unikraft no_std target, build core/alloc.
################################################################################
LIBWASMTIME_TARGET_JSON := $(LIBWASMTIME_BASE)/x86_64-unikraft.json

LIBWASMTIME_CARGOFLAGS-y += \
	--target=$(LIBWASMTIME_TARGET_JSON) \
	-Z build-std=core,alloc \
	-Z unstable-options \
	-Z json-target-spec

LIBWASMTIME_RUSTCFLAGS-y += \
	-Zallow-features=alloc_error_handler,allocator_api,concat_idents,bench_black_box,global_asm,try_reserve

################################################################################
# Sources
################################################################################
LIBWASMTIME_SRCS-y += $(LIBWASMTIME_BASE)/Cargo.toml

